### ISSUE TITLE
Was the check mark to hide TFP while not in POE removed?

### ISSUE THREAD

**Issue by leet0rz** [hexadezi/TraderForPoe#48]
I am pretty sure that before you could hide tradeforpoe trade windows while not in the POE window itself?

**Comment by hexadezi** [comment]
It is still there: Hide if not foreground

**Comment by leet0rz** [comment]
https://i.imgur.com/QKMyeQP.png

Am I blind? I do not see it

**Comment by hexadezi** [comment]
The problem is the scaling.

Try and update to 2.4. 

If the option is still not visible, then simply disable scaling for the application:
- [Windows scaling issues for high-DPI devices](https://support.microsoft.com/en-us/topic/windows-scaling-issues-for-high-dpi-devices-508483cd-7c59-0d08-12b0-960b99aa347d#:~:text=Right%2Dclick%20the%20application%2C%20select,high%20DPI%20settings%20check%20box.)

**Comment by leet0rz** [comment]
I tried that, did not work either. Could you let us just change the size of the window or maximize the size of the window? 
It looks like this currently:
https://i.imgur.com/qYZnNhI.png

**Comment by hexadezi** [comment]
I can not reproduce your scaling.

As a workaround you can edit the config file.

- Go to %localappdata%\TraderForPoe\TraderForPoe.exe_StrongName_li34f3hactba4l3akbehkrcuzgd01znu\2.4.0.0
- Edit user.config
- Set the value to true

```
<setting name="HideIfPoeNotForeGround" serializeAs="String">
      <value>True</value>
</setting>
```

**Comment by leet0rz** [comment]
Thanks. I just tabbed through the settings blindly pressing space until it all worked out. Please let us drag the window to a size of our liking as that would fix the issue too.
